; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Garden Gem"
#define MyAppVersion "1.6"
#define MyAppPublisher "Carrot"
#define MyAppURL "https://carrotstore.web.app"
#define MyAppExeName "Garden Gem.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".slot"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{870D48E9-6802-47AA-9333-826A9A391D5D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\trant\Desktop
OutputBaseFilename=Garden Gem
SetupIconFile=J:\Unity3d Project\Garden Gem\icons.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "J:\Build\Garden_Gem_ver6_win\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "J:\Build\Garden_Gem_ver6_win\Garden Gem.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "J:\Build\Garden_Gem_ver6_win\UnityCrashHandler64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "J:\Build\Garden_Gem_ver6_win\UnityPlayer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "J:\Build\Garden_Gem_ver6_win\GameAssembly.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "J:\Build\Garden_Gem_ver6_win\baselib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "J:\Build\Garden_Gem_ver6_win\Garden Gem_Data\*"; DestDir: "{app}\Garden Gem_Data"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "J:\Build\Garden_Gem_ver6_win\MonoBleedingEdge\*"; DestDir: "{app}\MonoBleedingEdge"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

